# Packaging pipeline for the following distros - produces amd64/arm/arm64 packages for:
#  - Debian 9
#  - Ubuntu 18.04
#  - Ubuntu 20.04

name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(Date:yyyyMMdd)$(Rev:rr)

parameters:
  - name: performSigning
    type: boolean
    displayName: 'Perform code signing'
    default: true
  - name: buildTargets
    type: object
    default:
      - ubuntu2004_amd64
        variantName: ubuntu20.04
        friendlyVariantName: ubuntu2004
        architecture: amd64
        containerPath: $(CONTAINER_REGISTRY)/ubuntu20.04-dev-amd64:latest
        platform: linux/amd64
      - ubuntu2004_arm64
        variantName: ubuntu20.04
        friendlyVariantName: ubuntu2004
        architecture: arm64
        containerPath: $(CONTAINER_REGISTRY)/ubuntu20.04-dev-arm64:latest
        platform: linux/arm64/v8
      - ubuntu2004_arm
        variantName: ubuntu20.04
        friendlyVariantName: ubuntu2004
        architecture: arm
        containerPath: $(CONTAINER_REGISTRY)/ubuntu20.04-dev-arm64:latest
        platform: linux/arm/v7
        ignoreTestFailures: true
      - ubuntu1804_amd64
        variantName: ubuntu18.04
        friendlyVariantName: ubuntu1804
        architecture: amd64
        containerPath: $(CONTAINER_REGISTRY)/ubuntu18.04-dev-amd64:latest
        platform: linux/amd64
      - ubuntu1804_arm64
        variantName: ubuntu18.04
        friendlyVariantName: ubuntu1804
        architecture: arm64
        containerPath: $(CONTAINER_REGISTRY)/ubuntu18.04-dev-arm64:latest
        platform: linux/arm64/v8
      - ubuntu1804_arm
        variantName: ubuntu18.04
        friendlyVariantName: ubuntu1804
        architecture: arm
        containerPath: $(CONTAINER_REGISTRY)/ubuntu18.04-dev-arm64:latest
        platform: linux/arm/v7
      - debian9_amd64
        variantName: debian9
        friendlyVariantName: debian9
        architecture: amd64
        containerPath: $(CONTAINER_REGISTRY)/debian9-dev-amd64:latest
        platform: linux/amd64
      - debian9_arm64
        variantName: debian9
        friendlyVariantName: debian9
        architecture: arm64
        containerPath: $(CONTAINER_REGISTRY)/debian9-dev-arm64:latest
        platform: linux/arm64/v8
      - debian9_arm
        variantName: debian9
        friendlyVariantName: debian9
        architecture: arm
        containerPath: $(CONTAINER_REGISTRY)/debian9-dev-arm:latest
        platform: linux/arm/v7

variables:
  SERVICE_CONNECTION: OSConfig-ACR
  CONTAINER_REGISTRY: osconfig.azurecr.io

trigger:
  branches:
    include:
    - main
pr: none

stages:
- template: stages/source_build.yaml
  parameters:
    containerPath: $(CONTAINER_REGISTRY)/ubuntu20.04-dev-amd64:latest
    publishArtifact: true

- template: stages/binary_build.yaml
  parameters:
    variantName: ubuntu20.04
    friendlyVariantName: ubuntu2004
    architecture: amd64_debug
    containerPath: $(CONTAINER_REGISTRY)/ubuntu20.04-dev-amd64:latest
    platform: linux/amd64
    performCoverage: true
    ignoreTestFailures: true
    publishArtifact: false

- ${{ each target in parameters.buildTargets }}:
  - template: stages/binary_build.yaml
    parameters:
      variantName: ${{ target.variantName }}
      friendlyVariantName: ${{ target.friendlyVariantName }}
      architecture: ${{ target.architecture }}
      containerPath: ${{ target.containerPath }}
      platform: ${{ target.platform }}

- template: stages/binary_signing.yaml
  parameters:
    performSigning: ${{ parameters.performSigning }}
    vaultName: $(VaultName)
    aadCertificateName: $(AADCertificateName)
    esrpCertificateName: $(ESRPCertificateName)
    dependsOn:
    - ${{ each target in parameters.buildTargets }}:
      - binary_${{target.friendlyVariantName}}${{target.architecture }}