trigger: none
pr: none

parameters:
- name: BUILD_UBUNTU2004_AMD64
  displayName: 'Ubuntu 20.04 AMD64 Dev Container'
  type: boolean
  default: false
- name: BUILD_UBUNTU2004_ARM
  displayName: 'Ubuntu 20.04 ARM Dev Container'
  type: boolean
  default: false
- name: BUILD_UBUNTU2004_ARM64
  displayName: 'Ubuntu 20.04 ARM64 Dev Container'
  type: boolean
  default: false
- name: BUILD_UBUNTU1804_AMD64
  displayName: 'Ubuntu 18.04 AMD64 Dev Container'
  type: boolean
  default: false
- name: BUILD_UBUNTU1804_ARM
  displayName: 'Ubuntu 18.04 ARM Dev Container'
  type: boolean
  default: false
- name: BUILD_UBUNTU1804_ARM64
  displayName: 'Ubuntu 18.04 ARM64 Dev Container'
  type: boolean
  default: false
- name: BUILD_DEBIAN9_AMD64
  displayName: 'Debian 9 AMD64 Dev Container'
  type: boolean
  default: false
- name: BUILD_DEBIAN9_ARM
  displayName: 'Debian 9 ARM Dev Container'
  type: boolean
  default: false
- name: BUILD_DEBIAN9_ARM64
  displayName: 'Debian 9 ARM64 Dev Container'
  type: boolean
  default: false
- name: BUILD_MARINERV1_AMD64
  displayName: 'Mariner v1 AMD64 Dev Container'
  type: boolean
  default: false

variables:
  SERVICE_CONNECTION: OSConfig-ACR
  CONTAINER_REGISTRY: osconfig.azurecr.io

stages:

- ${{ if eq(parameters.BUILD_UBUNTU2004_AMD64, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: ubuntu20.04-dev-amd64
      dockerFilePath: devops/docker/ubuntu20.04-amd64/Dockerfile

- ${{ if eq(parameters.BUILD_UBUNTU2004_ARM, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: ubuntu20.04-dev-arm
      dockerFilePath: devops/docker/ubuntu20.04-arm/Dockerfile

- ${{ if eq(parameters.BUILD_UBUNTU2004_ARM64, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: ubuntu20.04-dev-arm64
      dockerFilePath: devops/docker/ubuntu20.04-arm64/Dockerfile

- ${{ if eq(parameters.BUILD_UBUNTU1804_AMD64, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: ubuntu18.04-dev-amd64
      dockerFilePath: devops/docker/ubuntu18.04-amd64/Dockerfile

- ${{ if eq(parameters.BUILD_UBUNTU1804_ARM, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: ubuntu18.04-dev-arm
      dockerFilePath: devops/docker/ubuntu18.04-arm/Dockerfile

- ${{ if eq(parameters.BUILD_UBUNTU1804_ARM64, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: ubuntu18.04-dev-arm64
      dockerFilePath: devops/docker/ubuntu18.04-arm64/Dockerfile

- ${{ if eq(parameters.BUILD_DEBIAN9_AMD64, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: debian9-dev-amd64
      dockerFilePath: devops/docker/ubuntu20.04-amd64/Dockerfile

- ${{ if eq(parameters.BUILD_DEBIAN9_ARM, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: debian9-dev-arm
      dockerFilePath: devops/docker/ubuntu20.04-arm/Dockerfile

- ${{ if eq(parameters.BUILD_DEBIAN9_ARM64, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: debian9-dev-arm64
      dockerFilePath: devops/docker/ubuntu20.04-arm64/Dockerfile

- ${{ if eq(parameters.BUILD_MARINERV1_AMD64, True) }}:
  - template: stages/create_container.yaml
    parameters:
      repoName: marinerv1-dev-amd64
      dockerFilePath: devops/docker/marinerv1-amd64/Dockerfile
